package uz.zero.shopapp



enum class ErrorCode(val code: Int) {
    USER_NOT_FOUND(100),
    USER_ALREADY_EXISTS(101),
    INVALID_FULLNAME_EXCEPTION(102),
    INVALID_USERNAME_EXCEPTION(103),

    CATEGORY_NOT_FOUND(200),
    PRODUCT_NOT_FOUND(201),
    TRANSACTION_NOT_FOUND(202),
    INVALID_CATEGORYNAME_EXCEPTION(203),
    INVALID_ORDER_EXCEPTION(204),
    INVALID_LOCALIZEDNAME_EXCEPTION(205),

    INSUFFICIENT_BALANCE(300),
    INSUFFICIENT_PRODUCT(301),
    INVALID_AMOUNT(302),


}